import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";
import esbuildSvelte from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Plugin: SVG Quick Editor (Obsidian)
*/
`;

const prod = process.argv[2] === "production";

const copyCssPlugin = {
	name: "copy-css",
	setup(build) {
		build.onEnd(() => {
			try {
				if (fs.existsSync("main.css")) {
					fs.copyFileSync("main.css", "styles.css");
					console.log("Copied main.css to styles.css successfully (Anti-Zombie-CSS).");
				} else if (fs.existsSync("src/styles.css")) {
					fs.copyFileSync("src/styles.css", "styles.css");
					console.log("Copied src/styles.css to styles.css successfully.");
				}
			} catch (e) {
				console.error("Failed to copy stylesheet:", e);
			}
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [
		esbuildSvelte({
			compilerOptions: { css: "injected" },
			preprocess: sveltePreprocess(),
		}),
		copyCssPlugin,
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
