import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";
import esbuildSvelte from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Plugin: SVG Quick Editor (Obsidian)
*/
`;

const prod = process.argv[2] === "production";

/**
 * Obsidian Community Plugin Pre-build Compliance Guard:
 * Automatically checks for Obsidian Portal Scanner rules and aborts the build
 * immediately if any compliance violations (e.g. "Obsidian" in description,
 * unsafe innerHTML, navigator.platform, deprecated keyCode, or !important) are detected.
 */
const portalCompliancePlugin = {
	name: "portal-compliance-guard",
	setup(build) {
		build.onStart(() => {
			console.log("[PortalGuard] Verifying Obsidian developer guidelines compliance...");

			// 1. Verify manifest.json
			if (fs.existsSync("manifest.json")) {
				const manifest = JSON.parse(fs.readFileSync("manifest.json", "utf-8"));
				const desc = manifest.description || "";
				if (/\bobsidian\b/i.test(desc)) {
					throw new Error(
						`[BUILD ERROR] Manifest description must NOT include the word "Obsidian"! ` +
						`(Redundant in Obsidian plugin directory: "${desc}").`
					);
				}
				if (/^(a1-|A1)/.test(manifest.id || "")) {
					throw new Error(
						`[BUILD ERROR] Manifest ID must NOT start with personal prefix a1- / A1! ("${manifest.id}").`
					);
				}
			}

			// 2. Scan source files for banned patterns
			const scanDirs = ["src"];
			const checkSourceFile = (filePath) => {
				const content = fs.readFileSync(filePath, "utf-8");
				if (/navigator\.platform/g.test(content)) {
					throw new Error(
						`[BUILD ERROR in ${filePath}]: Avoid using navigator.platform! Use Platform.isMacOS from obsidian instead.`
					);
				}
				if (/\.innerHTML\s*=/g.test(content)) {
					throw new Error(
						`[BUILD ERROR in ${filePath}]: Unsafe assignment to innerHTML detected! Use DOMParser or textContent instead.`
					);
				}
				if (/\bkeyCode\b/g.test(content)) {
					throw new Error(
						`[BUILD ERROR in ${filePath}]: Deprecated KeyboardEvent.keyCode detected! Use e.key or e.code instead.`
					);
				}
			};

			const walkDir = (dir) => {
				if (!fs.existsSync(dir)) return;
				for (const item of fs.readdirSync(dir)) {
					const p = path.join(dir, item);
					if (fs.statSync(p).isDirectory()) {
						walkDir(p);
					} else if (p.endsWith(".ts") && !p.endsWith(".test.ts")) {
						checkSourceFile(p);
					}
				}
			};
			for (const d of scanDirs) walkDir(d);

			// 3. Scan styles.css for !important
			if (fs.existsSync("src/styles.css")) {
				const css = fs.readFileSync("src/styles.css", "utf-8");
				if (/!important/g.test(css)) {
					throw new Error(
						`[BUILD ERROR in src/styles.css]: Avoid using !important in styles! Override styles by increasing selector specificity or using CSS variables.`
					);
				}
			}

			console.log("[PortalGuard] All compliance checks passed successfully ✅");
		});
	},
};

const copyCssPlugin = {
	name: "copy-css",
	setup(build) {
		build.onEnd(() => {
			try {
				if (fs.existsSync("main.css")) {
					fs.copyFileSync("main.css", "styles.css");
					console.log("Copied main.css to styles.css successfully (Anti-Zombie-CSS).");
				} else if (fs.existsSync("src/styles.css")) {
					fs.copyFileSync("src/styles.css", "styles.css");
					console.log("Copied src/styles.css to styles.css successfully.");
				}
			} catch (e) {
				console.error("Failed to copy stylesheet:", e);
			}
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [
		portalCompliancePlugin,
		esbuildSvelte({
			compilerOptions: { css: "injected" },
			preprocess: sveltePreprocess(),
		}),
		copyCssPlugin,
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
