/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Plugin: SVG Quick Editor (Obsidian)
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  commitText: () => commitText,
  default: () => A1SvgQuickEditorPlugin,
  getLocaleStrings: () => getLocaleStrings,
  isDiagramSvg: () => isDiagramSvg,
  resolveHit: () => resolveHit
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/svgCard.ts
function localName(el) {
  return el.localName || el.tagName.toLowerCase().replace(/^.*:/, "");
}
function isTextNode(el) {
  const name = localName(el);
  return name === "text" || name === "tspan";
}
function countTexts(el) {
  return el.querySelectorAll("text").length;
}
function getCoords(el) {
  const x = num(el.getAttribute("x")) ?? num(el.querySelector("tspan")?.getAttribute("x") ?? null);
  const y = num(el.getAttribute("y")) ?? num(el.querySelector("tspan")?.getAttribute("y") ?? null);
  if (x != null && y != null)
    return { x, y };
  const tr = el.getAttribute("transform") ?? "";
  const m = tr.match(/translate\(\s*([-\d.]+)\s*[ ,]\s*([-\d.]+)\s*\)/);
  if (m)
    return { x: parseFloat(m[1]), y: parseFloat(m[2]) };
  return null;
}
function isCardSizedRect(rect, svg) {
  const w = num(rect.getAttribute("width"));
  const h = num(rect.getAttribute("height"));
  if (w == null || h == null || w <= 0 || h <= 0)
    return false;
  if (!svg)
    return true;
  const vb = (svg.getAttribute("viewBox") ?? svg.getAttribute("viewbox") ?? "").trim().split(/[\s,]+/);
  const svgW = vb.length === 4 ? parseFloat(vb[2]) : num(svg.getAttribute("width"));
  const svgH = vb.length === 4 ? parseFloat(vb[3]) : num(svg.getAttribute("height"));
  if (svgW && svgH && w >= svgW * 0.85 && h >= svgH * 0.85)
    return false;
  return true;
}
function wrapInChipGroup(elA, elB) {
  const parent = elA.parentElement;
  if (!parent)
    return elA;
  const doc = elA.ownerDocument || document;
  const g = doc.createElementNS("http://www.w3.org/2000/svg", "g");
  g.setAttribute("class", "a1-svg-chip");
  const isFollowing = typeof elA.compareDocumentPosition === "function" ? (elA.compareDocumentPosition(elB) & 4) !== 0 : true;
  const first = isFollowing ? elA : elB;
  const second = first === elA ? elB : elA;
  parent.insertBefore(g, first);
  g.appendChild(first);
  g.appendChild(second);
  return g;
}
function findAdjacentBadgeRect(textEl) {
  const parent = textEl.parentElement;
  if (!parent)
    return null;
  const coords = getCoords(textEl);
  if (!coords)
    return null;
  const tx = coords.x;
  const ty = coords.y;
  const rects = Array.from(parent.children).filter((c) => localName(c) === "rect");
  for (const r of rects) {
    const w = num(r.getAttribute("width")) ?? 0;
    const h = num(r.getAttribute("height")) ?? 0;
    if (w <= 0 || w > 220 || h <= 0 || h > 65)
      continue;
    if (w <= 4 || h <= 4)
      continue;
    const rx = num(r.getAttribute("x")) ?? 0;
    const ry = num(r.getAttribute("y")) ?? 0;
    if (tx >= rx - 15 && tx <= rx + w + 15 && ty >= ry && ty <= ry + h + 8) {
      return r;
    }
  }
  return null;
}
function resolveCloneTarget(target, clientX, clientY) {
  if (!target)
    return null;
  const isSvgRoot = typeof SVGSVGElement !== "undefined" && target instanceof SVGSVGElement || localName(target) === "svg";
  if (isSvgRoot)
    return null;
  const svg = target.closest("svg");
  if (!svg)
    return null;
  if (localName(target) === "rect" && !isCardSizedRect(target, svg)) {
    return null;
  }
  const textNode = asText(target);
  if (textNode) {
    let dedicatedChip = null;
    let curr = textNode.parentElement;
    while (curr && curr !== svg) {
      if (localName(curr) === "g") {
        if (countTexts(curr) === 1) {
          dedicatedChip = curr;
        } else {
          break;
        }
      }
      curr = curr.parentElement;
    }
    if (dedicatedChip) {
      return dedicatedChip;
    }
    const badge = findAdjacentBadgeRect(textNode);
    if (badge) {
      return wrapInChipGroup(badge, textNode);
    }
    return textNode;
  }
  if (localName(target) === "rect") {
    const w = num(target.getAttribute("width")) ?? 0;
    const h = num(target.getAttribute("height")) ?? 0;
    const isSmall = w > 0 && w <= 220 && h > 0 && h <= 65 && w > 4 && h > 4;
    if (isSmall) {
      const parentG = target.closest("g");
      if (parentG && parentG !== svg && countTexts(parentG) === 1) {
        return parentG;
      }
      const associatedText = findTextInCard(target, clientX, clientY);
      if (associatedText && associatedText.parentElement === target.parentElement) {
        return wrapInChipGroup(target, associatedText);
      }
    }
    const cardGroup = target.closest("g");
    if (cardGroup && cardGroup !== svg) {
      return cardGroup;
    }
  }
  const name = localName(target);
  if (name === "circle" || name === "path") {
    const parentG = target.closest("g");
    if (parentG && parentG !== svg && countTexts(parentG) === 1) {
      return parentG;
    }
  }
  let node = target;
  while (node && node !== svg) {
    if (node.hasAttribute("data-a1-card"))
      return node;
    if (localName(node) === "g") {
      const rects = Array.from(node.querySelectorAll("rect")).filter((r) => isCardSizedRect(r, svg));
      if (rects.length >= 1)
        return node;
    }
    node = node.parentElement;
  }
  return null;
}
function findCard(textEl) {
  const textRoot = localName(textEl) === "tspan" ? textEl.closest("text") ?? textEl : textEl;
  let node = textRoot;
  let singleTextGroup = null;
  let multiTextCard = null;
  const svg = textRoot.closest("svg");
  while (node) {
    if (node.hasAttribute("data-a1-card"))
      return node;
    const name = localName(node);
    if (name === "g") {
      if (singleTextGroup == null && countTexts(node) === 1) {
        singleTextGroup = node;
      }
      if (multiTextCard == null) {
        const rects = Array.from(node.querySelectorAll("rect")).filter((r) => isCardSizedRect(r, svg));
        if (rects.length >= 1) {
          multiTextCard = node;
        }
      }
    }
    if (name === "svg")
      break;
    node = node.parentElement;
  }
  return singleTextGroup ?? multiTextCard ?? textRoot;
}
function collectOwned(card, textEl) {
  const textRoot = localName(textEl) === "tspan" ? textEl.closest("text") ?? textEl : textEl;
  let curr = textRoot.parentElement;
  const svg = textRoot.closest("svg");
  let dedicatedChip = null;
  while (curr && curr !== svg) {
    if (localName(curr) === "g") {
      if (countTexts(curr) === 1) {
        dedicatedChip = curr;
      } else {
        break;
      }
    }
    curr = curr.parentElement;
  }
  if (dedicatedChip) {
    return [dedicatedChip];
  }
  return [textRoot];
}
function asText(node) {
  if (!node)
    return null;
  const el = node.closest("text, tspan") ?? (isTextNode(node) ? node : null);
  if (!el)
    return null;
  const text = localName(el) === "text" ? el : el.closest("text");
  if (text && localName(text) === "text")
    return text;
  return null;
}
function pickClosestText(texts, clientX, clientY) {
  if (texts.length === 0)
    throw new Error("pickClosestText called with empty array");
  if (clientX == null || clientY == null) {
    return texts[0];
  }
  let best = texts[0];
  let bestDist = Infinity;
  for (const t of texts) {
    let cx = num(t.getAttribute("x")) ?? 0;
    let cy = num(t.getAttribute("y")) ?? 0;
    if (typeof t.getBoundingClientRect === "function") {
      const r = t.getBoundingClientRect();
      if (r.width > 0 || r.height > 0) {
        cx = r.left + r.width / 2;
        cy = r.top + r.height / 2;
      }
    }
    const d = Math.hypot(cx - clientX, cy - clientY);
    if (d < bestDist) {
      bestDist = d;
      best = t;
    }
  }
  return best;
}
function findTextInCard(start, clientX, clientY) {
  if (!start)
    return null;
  const direct = asText(start);
  if (direct)
    return direct;
  const isSvg = typeof SVGSVGElement !== "undefined" && start instanceof SVGSVGElement || localName(start) === "svg";
  const svg = isSvg ? start : start.closest("svg") ?? start.querySelector("svg");
  if (!svg)
    return null;
  const descendants = Array.from(start.querySelectorAll("text")).filter((t) => asText(t) !== null);
  if (descendants.length === 1)
    return descendants[0];
  if (descendants.length > 1) {
    return pickClosestText(descendants, clientX, clientY);
  }
  let curr = start.parentElement;
  while (curr && curr !== svg) {
    const name2 = localName(curr);
    if (name2 === "g" || curr.hasAttribute("data-a1-card")) {
      const texts = Array.from(curr.querySelectorAll("text")).filter((t) => asText(t) !== null);
      if (texts.length === 1)
        return texts[0];
      if (texts.length > 1) {
        return pickClosestText(texts, clientX, clientY);
      }
    }
    curr = curr.parentElement;
  }
  const name = localName(start);
  if (name === "rect") {
    const rx = num(start.getAttribute("x")) ?? 0;
    const ry = num(start.getAttribute("y")) ?? 0;
    const rw = num(start.getAttribute("width"));
    const rh = num(start.getAttribute("height"));
    if (rw != null && rh != null && rw > 0 && rh > 0) {
      const allTexts = Array.from(svg.querySelectorAll("text")).filter((t) => asText(t) !== null);
      const insideTexts = allTexts.filter((t) => {
        const pt = getCoords(t);
        if (!pt)
          return false;
        return pt.x >= rx - 8 && pt.x <= rx + rw + 8 && pt.y >= ry - 8 && pt.y <= ry + rh + 8;
      });
      if (insideTexts.length === 1)
        return insideTexts[0];
      if (insideTexts.length > 1) {
        return pickClosestText(insideTexts, clientX, clientY);
      }
    }
  }
  const allSvgTexts = Array.from(svg.querySelectorAll("text")).filter((t) => asText(t) !== null);
  if (allSvgTexts.length === 1)
    return allSvgTexts[0];
  if (allSvgTexts.length > 1 && clientX != null && clientY != null) {
    return pickClosestText(allSvgTexts, clientX, clientY);
  }
  return allSvgTexts[0] ?? null;
}
function resolveHit(start) {
  let textEl = start;
  if (!isTextNode(textEl)) {
    textEl = asText(start) ?? findTextInCard(start);
  }
  if (!textEl || !isTextNode(textEl))
    return null;
  const card = findCard(textEl.localName === "tspan" || localName(textEl) === "tspan" ? textEl.closest("text") ?? textEl : textEl);
  return { textEl, card, owned: collectOwned(card, textEl) };
}
function readText(textEl) {
  return (textEl.textContent ?? "").replace(/\u00a0/g, " ");
}
function writeText(textEl, value) {
  const name = localName(textEl);
  if (name === "text") {
    const tspans = Array.from(textEl.children).filter((c) => localName(c) === "tspan");
    if (tspans.length === 1 && textEl.childNodes.length === 1) {
      tspans[0].textContent = value;
      return;
    }
    if (tspans.length > 1) {
      tspans[0].textContent = value;
      for (let i = 1; i < tspans.length; i++)
        tspans[i].remove();
      return;
    }
  }
  textEl.textContent = value;
}
function commitText(hit, raw) {
  const value = raw.replace(/\u00a0/g, " ").trim();
  if (value.length === 0) {
    for (const el of hit.owned) {
      el.remove();
    }
    return { action: "delete", removed: hit.owned };
  }
  writeText(hit.textEl, value);
  return { action: "update", removed: [] };
}
var cloneSeq = 0;
function cloneCard(card, dx, dy) {
  const clone = card.cloneNode(true);
  cloneSeq += 1;
  const stamp = `a1c${cloneSeq}`;
  nudge(clone, dx, dy);
  rewriteIds(card, clone, stamp);
  return clone;
}
function num(raw) {
  if (raw == null || raw.trim() === "")
    return null;
  const n = parseFloat(raw);
  return Number.isFinite(n) ? n : null;
}
function nudge(el, dx, dy) {
  const name = localName(el);
  if (name === "g" || name === "svg" || name === "use" || el.hasAttribute("transform")) {
    const prev = el.getAttribute("transform") ?? "";
    const m = prev.match(/translate\(\s*([-\d.]+)\s*[ ,]\s*([-\d.]+)\s*\)\s*$/);
    if (m) {
      const x = parseFloat(m[1]) + dx;
      const y = parseFloat(m[2]) + dy;
      el.setAttribute("transform", prev.slice(0, m.index) + `translate(${trimNum(x)} ${trimNum(y)})`);
    } else {
      el.setAttribute("transform", `${prev} translate(${trimNum(dx)} ${trimNum(dy)})`.trim());
    }
    return;
  }
  shiftAttr(el, "x", dx);
  shiftAttr(el, "y", dy);
  shiftAttr(el, "cx", dx);
  shiftAttr(el, "cy", dy);
  shiftAttr(el, "x1", dx);
  shiftAttr(el, "y1", dy);
  shiftAttr(el, "x2", dx);
  shiftAttr(el, "y2", dy);
  if (name === "text") {
    for (const tspan of Array.from(el.querySelectorAll("tspan"))) {
      shiftAttr(tspan, "x", dx);
      shiftAttr(tspan, "y", dy);
    }
  }
}
function shiftAttr(el, attr, delta) {
  if (delta === 0 || !el.hasAttribute(attr))
    return;
  const n = num(el.getAttribute(attr));
  if (n == null)
    return;
  el.setAttribute(attr, trimNum(n + delta));
}
function trimNum(n) {
  const r = Math.round(n * 100) / 100;
  return String(r);
}
function rewriteIds(source, clone, stamp) {
  const map = /* @__PURE__ */ new Map();
  const walk = (el) => {
    const id = el.getAttribute("id");
    if (id) {
      const next = `${id}-${stamp}`;
      map.set(id, next);
      el.setAttribute("id", next);
    }
    for (const child of Array.from(el.children))
      walk(child);
  };
  walk(clone);
  if (map.size === 0)
    return;
  const retarget = (el) => {
    for (const attr of ["href", "xlink:href", "fill", "stroke", "filter", "clip-path", "mask"]) {
      const v = el.getAttribute(attr);
      if (!v)
        continue;
      el.setAttribute(attr, v.replace(/url\(#([^)]+)\)|#([A-Za-z_][\w:.-]*)/g, (m, urlId, hashId) => {
        const id = urlId || hashId;
        const next = map.get(id);
        if (!next)
          return m;
        return urlId ? `url(#${next})` : `#${next}`;
      }));
    }
    for (const child of Array.from(el.children))
      retarget(child);
  };
  retarget(clone);
}
function escapeText(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
function escapeAttr(s) {
  return escapeText(s).replace(/"/g, "&quot;");
}
function serializeSvg(el) {
  const name = el.localName || el.tagName;
  const attrs = [];
  for (let i = 0; i < el.attributes.length; i++) {
    const a = el.attributes[i];
    if (a.name === "data-a1-svg-path")
      continue;
    if (a.name === "class") {
      const cleaned = a.value.split(/\s+/).filter((c) => c && c !== "a1-svg-hover-text").join(" ");
      if (!cleaned)
        continue;
      attrs.push(`class="${escapeAttr(cleaned)}"`);
      continue;
    }
    attrs.push(`${a.name}="${escapeAttr(a.value)}"`);
  }
  const open = attrs.length ? `<${name} ${attrs.join(" ")}>` : `<${name}>`;
  let inner = "";
  for (const node of Array.from(el.childNodes)) {
    if (node.nodeType === 1)
      inner += serializeSvg(node);
    else if (node.nodeType === 3)
      inner += escapeText(node.textContent ?? "");
  }
  return `${open}${inner}</${name}>`;
}

// src/editorOverlay.ts
function openTextOverlay(parent, opts) {
  const input = document.createElement("input");
  input.type = "text";
  input.className = "a1-svg-edit";
  input.value = opts.value;
  input.setAttribute("aria-label", "Edit SVG text");
  const width = Math.max(opts.rect.width + 24, 80);
  const height = Math.max(opts.rect.height + 6, 26);
  input.style.left = `${Math.round(opts.rect.left)}px`;
  input.style.top = `${Math.round(opts.rect.top - 2)}px`;
  input.style.width = `${Math.round(width)}px`;
  input.style.height = `${Math.round(height)}px`;
  input.style.fontSize = opts.fontSize || "14px";
  input.style.fontFamily = opts.fontFamily || "inherit";
  input.style.color = opts.color || "inherit";
  let closed = false;
  let composing = false;
  const suppressAlt = (e) => {
    if (e.key === "Alt" || e.keyCode === 18) {
      e.preventDefault();
    }
  };
  window.addEventListener("keyup", suppressAlt, { capture: true });
  const close = () => {
    if (closed)
      return;
    closed = true;
    window.removeEventListener("keyup", suppressAlt, { capture: true });
    input.remove();
  };
  const commit = () => {
    if (closed)
      return;
    const value = input.value;
    close();
    opts.onCommit(value);
  };
  const cancel = () => {
    if (closed)
      return;
    close();
    opts.onCancel();
  };
  input.addEventListener("compositionstart", () => {
    composing = true;
  });
  input.addEventListener("compositionend", () => {
    composing = false;
  });
  input.addEventListener("keydown", (e) => {
    if (e.isComposing || composing || e.keyCode === 229)
      return;
    if (e.key === "Enter") {
      e.preventDefault();
      e.stopPropagation();
      commit();
    } else if (e.key === "Escape") {
      e.preventDefault();
      e.stopPropagation();
      cancel();
    }
  });
  const mountTime = Date.now();
  input.addEventListener("blur", () => {
    if (closed)
      return;
    if (typeof document !== "undefined" && !document.hasFocus()) {
      return;
    }
    if (Date.now() - mountTime < 350) {
      input.focus();
      return;
    }
    window.setTimeout(() => {
      if (!closed)
        commit();
    }, 60);
  });
  parent.appendChild(input);
  input.focus();
  input.select();
  return { input, close };
}

// src/svgSource.ts
var SVG_RE = /<svg\b[^>]*>[\s\S]*?<\/svg>/gi;
function findSvgSpans(markdown) {
  const spans = [];
  SVG_RE.lastIndex = 0;
  let m;
  while ((m = SVG_RE.exec(markdown)) !== null) {
    spans.push({ start: m.index, end: m.index + m[0].length, inner: m[0] });
  }
  return spans;
}
function matchSpan(markdown, domIndex, marker) {
  const spans = findSvgSpans(markdown);
  if (marker) {
    const hit = spans.find((s) => s.inner.includes(`data-a1-svg="${marker}"`) || s.inner.includes(`data-a1-svg='${marker}'`));
    if (hit)
      return hit;
  }
  if (domIndex < 0 || domIndex >= spans.length)
    return null;
  return spans[domIndex];
}
function spliceSvg(markdown, span, replacement) {
  return markdown.slice(0, span.start) + replacement + markdown.slice(span.end);
}
function ensureMarker(svgMarkup, marker) {
  if (/data-a1-svg=/.test(svgMarkup))
    return svgMarkup;
  return svgMarkup.replace(/<svg\b/, `<svg data-a1-svg="${marker}"`);
}

// src/svgHistory.ts
function cleanSvgHtml(html) {
  return html.replace(/\s*class="[^"]*a1-svg-hover-[^"]*"/g, "").replace(/\s*a1-svg-hover-text/g, "").replace(/\s*a1-svg-hover-image/g, "").replace(/\s+data-a1-[a-z0-9_-]+(?:="[^"]*")?/g, "").trim();
}
var SvgHistoryManager = class {
  constructor() {
    this.initialContent = /* @__PURE__ */ new WeakMap();
    this.undoStacks = /* @__PURE__ */ new WeakMap();
    this.redoStacks = /* @__PURE__ */ new WeakMap();
    this.maxStackSize = 50;
    this.activeSvg = null;
  }
  setActiveSvg(svg) {
    this.activeSvg = svg;
    if (svg && !this.initialContent.has(svg)) {
      this.initialContent.set(svg, cleanSvgHtml(svg.innerHTML));
      this.undoStacks.set(svg, []);
      this.redoStacks.set(svg, []);
    }
  }
  getActiveSvg() {
    if (this.activeSvg && this.activeSvg.isConnected) {
      return this.activeSvg;
    }
    if (typeof document !== "undefined") {
      const modalSvg = document.querySelector(".svg-lightbox-body svg, .svg-lightbox-content svg, .a1-svg-modal-body svg");
      if (modalSvg) {
        this.setActiveSvg(modalSvg);
        return modalSvg;
      }
    }
    return null;
  }
  /**
   * Records a snapshot of the SVG content before mutation so it can be reverted via Undo.
   */
  recordSnapshot(svg) {
    this.setActiveSvg(svg);
    const currentHtml = cleanSvgHtml(svg.innerHTML);
    const stack = this.undoStacks.get(svg) || [];
    if (stack.length === 0 || stack[stack.length - 1] !== currentHtml) {
      stack.push(currentHtml);
      if (stack.length > this.maxStackSize) {
        stack.shift();
      }
      this.undoStacks.set(svg, stack);
    }
    this.redoStacks.set(svg, []);
  }
  undo(svg) {
    const target = svg ?? this.getActiveSvg();
    if (!target)
      return false;
    const undoStack = this.undoStacks.get(target);
    if (!undoStack || undoStack.length === 0)
      return false;
    const currentHtml = cleanSvgHtml(target.innerHTML);
    const prevHtml = undoStack.pop();
    const redoStack = this.redoStacks.get(target) || [];
    redoStack.push(currentHtml);
    this.redoStacks.set(target, redoStack);
    target.innerHTML = prevHtml;
    return true;
  }
  redo(svg) {
    const target = svg ?? this.getActiveSvg();
    if (!target)
      return false;
    const redoStack = this.redoStacks.get(target);
    if (!redoStack || redoStack.length === 0)
      return false;
    const currentHtml = cleanSvgHtml(target.innerHTML);
    const nextHtml = redoStack.pop();
    const undoStack = this.undoStacks.get(target) || [];
    undoStack.push(currentHtml);
    this.undoStacks.set(target, undoStack);
    target.innerHTML = nextHtml;
    return true;
  }
  isDirty(svg) {
    const target = svg ?? this.getActiveSvg();
    if (!target)
      return false;
    const undoStack = this.undoStacks.get(target);
    if (!undoStack || undoStack.length === 0) {
      return false;
    }
    const initial = this.initialContent.get(target);
    if (initial == null)
      return false;
    return cleanSvgHtml(target.innerHTML) !== cleanSvgHtml(initial);
  }
  getInitialContent(svg) {
    const target = svg ?? this.getActiveSvg();
    if (!target)
      return null;
    return this.initialContent.get(target) ?? null;
  }
  discard(svg) {
    const target = svg ?? this.getActiveSvg();
    if (!target)
      return;
    const initial = this.initialContent.get(target);
    if (initial != null) {
      target.innerHTML = initial;
    }
    this.clear(target);
  }
  markSaved(svg) {
    const target = svg ?? this.getActiveSvg();
    if (!target)
      return;
    this.initialContent.set(target, cleanSvgHtml(target.innerHTML));
    this.clear(target);
  }
  clear(svg) {
    const target = svg ?? this.getActiveSvg();
    if (target) {
      this.undoStacks.set(target, []);
      this.redoStacks.set(target, []);
    }
    if (this.activeSvg === target) {
      this.activeSvg = null;
    }
  }
};

// src/main.ts
var MARK = "data-a1-svg";
var SVG_PATH_ATTR = "data-a1-svg-path";
var DEFAULT_SETTINGS = {
  openEditorHotkey: "Ctrl+Shift+Alt+I"
};
function isDiagramSvg(el) {
  if (!el)
    return false;
  const isSvg = typeof SVGSVGElement !== "undefined" && el instanceof SVGSVGElement || (el.localName || el.tagName.toLowerCase()).endsWith("svg");
  if (!isSvg)
    return false;
  if (el.closest("button, .oit-floating-zoom-btn, .clickable-icon, .svg-lightbox-header, .a1-svg-modal-header, .nav-action-button, [class*='overlay'], [class*='toolbar'], .workspace-tab-header, .view-header")) {
    return false;
  }
  const cls = (el.getAttribute("class") || "").toLowerCase();
  if (cls.includes("svg-icon") || cls.includes("lucide") || cls.includes("oit-") || cls.includes("zoom") || cls.includes("icon")) {
    return false;
  }
  const w = parseFloat(el.getAttribute("width") || "0");
  const h = parseFloat(el.getAttribute("height") || "0");
  const vb = (el.getAttribute("viewBox") || el.getAttribute("viewbox") || "").trim().split(/[\s,]+/);
  const vbw = vb.length === 4 ? parseFloat(vb[2]) : 0;
  const vbh = vb.length === 4 ? parseFloat(vb[3]) : 0;
  if ((w > 0 && w <= 64 && h > 0 && h <= 64 || vbw > 0 && vbw <= 64 && vbh > 0 && vbh <= 64) && el.querySelectorAll("text").length === 0) {
    return false;
  }
  if (el.querySelectorAll("text").length === 0 && (w <= 64 || vbw <= 64)) {
    return false;
  }
  return true;
}
function getLocaleStrings() {
  let lang = "en";
  try {
    lang = ((0, import_obsidian.getLanguage)?.() || window.localStorage?.getItem("language") || window.moment?.locale() || "en").toLowerCase();
  } catch {
  }
  const isZh = lang === "zh" || lang.startsWith("zh-") || lang.startsWith("zh_");
  if (isZh) {
    return {
      modalTitleDefault: "SVG \u56FE\u50CF\u7F16\u8F91\u5668",
      modalTitleNamed: (name) => `SVG \u56FE\u50CF\u7F16\u8F91\u5668 \u2014 ${name}`,
      badgeEdit: "F2 / \u53CC\u51FB\u6587\u5B57\u7F16\u8F91",
      badgeDelete: "\u6E05\u7A7A\u6587\u5B57\u5373\u5220UI\u6846",
      badgeClone: "Alt + \u62D6\u62FD\u590D\u5236UI\u6846",
      badgeUndoRedo: "Ctrl+Z/Y \u64A4\u9500\u91CD\u505A",
      badgeAutoSave: "\u9000\u51FA\u786E\u8BA4\u4FDD\u5B58",
      closeTooltip: "\u5173\u95ED (Esc)",
      noticeSaved: (name) => `SVG \u5DF2\u4FDD\u5B58: ${name}`,
      noticeUndo: "\u5DF2\u64A4\u9500",
      noticeRedo: "\u5DF2\u91CD\u505A",
      confirmSaveTitle: "\u662F\u5426\u4FDD\u5B58\uFF1F",
      confirmSaveDesc: "\u5F53\u524D SVG \u56FE\u50CF\u5DF2\u6709\u6539\u52A8\uFF0C\u9000\u51FA\u524D\u662F\u5426\u4FDD\u5B58\u66F4\u6539\uFF1F",
      btnSave: "\u4FDD\u5B58 (Enter)",
      btnDiscard: "\u4E0D\u4FDD\u5B58 / \u653E\u5F03",
      btnCancel: "\u7EE7\u7EED\u7F16\u8F91 (Esc)",
      openInTab: "\u5728\u65B0\u6807\u7B7E\u9875\u6253\u5F00",
      noticeHoverSvgPrompt: "\u8BF7\u5C06\u9F20\u6807\u60AC\u6D6E\u5728\u7B14\u8BB0\u4E2D\u7684 SVG \u56FE\u7247\u4E0A\u65B9",
      noticeHoverTextPrompt: "\u8BF7\u5C06\u9F20\u6807\u60AC\u6D6E\u5728 SVG \u5361\u7247\u3001\u6587\u5B57\u6216\u56FE\u7247\u4E0A\u65B9",
      noticeCannotParse: "\u672A\u80FD\u89E3\u6790\u51FA\u6709\u6548\u7684 SVG \u6570\u636E",
      settingTabTitle: "A1 SVG Quick Editor \u8BBE\u7F6E",
      settingHotkeyName: "\u6253\u5F00 SVG \u56FE\u50CF\u7F16\u8F91\u5668\u5FEB\u6377\u952E",
      settingHotkeyDesc: "\u5F53\u9F20\u6807\u505C\u7559\u5728\u7B14\u8BB0\u4E2D\u7684 SVG \u56FE\u7247\u4E0A\u65F6\u6309\u4E0B\u6B64\u5FEB\u6377\u952E\uFF0C\u6253\u5F00\u5168\u5C4F\u4EA4\u4E92\u5F0F SVG \u7F16\u8F91\u5668\u5F39\u7A97\u3002\u9ED8\u8BA4\uFF1ACtrl+Shift+Alt+I\u3002\u5728\u8F93\u5165\u6846\u4E2D\u53EF\u76F4\u63A5\u6309\u4E0B\u60F3\u8981\u5F55\u5236\u7684\u5FEB\u6377\u952E\u3002",
      settingResetTooltip: "\u6062\u590D\u9ED8\u8BA4\u5FEB\u6377\u952E (Ctrl+Shift+Alt+I)",
      settingUpdatedNotice: (hk) => `SVG \u7F16\u8F91\u5FEB\u6377\u952E\u5DF2\u66F4\u65B0\u4E3A: ${hk}`,
      settingResetNotice: "\u5DF2\u6062\u590D\u9ED8\u8BA4\u5FEB\u6377\u952E: Ctrl+Shift+Alt+I"
    };
  }
  return {
    modalTitleDefault: "SVG Image Editor",
    modalTitleNamed: (name) => `SVG Image Editor \u2014 ${name}`,
    badgeEdit: "F2 / Double-click to Edit",
    badgeDelete: "Clear Text to Delete Box",
    badgeClone: "Alt + Drag to Duplicate",
    badgeUndoRedo: "Ctrl+Z/Y Undo/Redo",
    badgeAutoSave: "Save on Exit",
    closeTooltip: "Close (Esc)",
    noticeSaved: (name) => `SVG saved: ${name}`,
    noticeUndo: "Undone",
    noticeRedo: "Redone",
    confirmSaveTitle: "Save changes?",
    confirmSaveDesc: "The SVG image has been modified. Do you want to save changes before exiting?",
    btnSave: "Save (Enter)",
    btnDiscard: "Don't Save",
    btnCancel: "Keep Editing (Esc)",
    openInTab: "Open in Tab",
    noticeHoverSvgPrompt: "Please hover cursor over an SVG image in the note",
    noticeHoverTextPrompt: "Please hover cursor over an SVG card, text, or image",
    noticeCannotParse: "Failed to resolve valid SVG data",
    settingTabTitle: "A1 SVG Quick Editor Settings",
    settingHotkeyName: "Open SVG Image Editor Hotkey",
    settingHotkeyDesc: "Press this hotkey while hovering over an SVG image in any note to open the interactive SVG editor. Default: Ctrl+Shift+Alt+I. Type directly in the input box to record your hotkey.",
    settingResetTooltip: "Reset to default hotkey (Ctrl+Shift+Alt+I)",
    settingUpdatedNotice: (hk) => `SVG editor hotkey updated to: ${hk}`,
    settingResetNotice: "Reset to default hotkey: Ctrl+Shift+Alt+I"
  };
}
var A1SvgQuickEditorPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.history = new SvgHistoryManager();
    this.overlay = null;
    this.hovered = null;
    this.hoveredSvgTarget = null;
    this.lastPointerX = 0;
    this.lastPointerY = 0;
    this.dragging = null;
    this.activeModal = null;
  }
  async onload() {
    window.a1SvgQuickEditor = this;
    window.svgQuickEditor = this;
    this.addSettingTab(new A1SvgQuickEditorSettingTab(this.app, this));
    await this.loadSettings();
    this.registerDomEvent(window, "pointermove", (evt) => this.onPointerMove(evt), { capture: true });
    this.registerDomEvent(window, "pointerdown", (evt) => this.onPointerDown(evt), { capture: true });
    this.registerDomEvent(window, "pointerup", (evt) => this.onPointerUp(evt), { capture: true });
    this.registerDomEvent(window, "keydown", (evt) => this.onKeyDown(evt), { capture: true });
    this.registerDomEvent(window, "dblclick", (evt) => {
      const text = this.textFromEvent(evt) ?? (evt.target instanceof Element ? findTextInCard(evt.target, evt.clientX, evt.clientY) : null);
      if (text && this.isInteractiveSvg(text)) {
        evt.preventDefault();
        evt.stopPropagation();
        evt.stopImmediatePropagation();
        void this.beginEdit(text);
      }
    }, { capture: true });
    this.registerDomEvent(window, "click", (evt) => {
      if (this.overlay)
        return;
      const target = evt.target;
      if (!(target instanceof Element))
        return;
      const modalContainer = target.closest(".a1-svg-modal-body, .svg-lightbox-content");
      if (!modalContainer)
        return;
      const text = asText(target);
      if (text && this.isInteractiveSvg(text)) {
        evt.preventDefault();
        evt.stopPropagation();
        this.setHover(text);
        void this.beginEdit(text);
        return;
      }
      const cardText = findTextInCard(target, evt.clientX, evt.clientY);
      if (cardText && this.isInteractiveSvg(cardText)) {
        this.setHover(cardText);
      }
    }, { capture: true });
    this.addCommand({
      id: "edit-svg-text",
      name: "Edit SVG text under cursor (F2 / Inline)",
      callback: () => {
        void this.executeEditSvgText();
      }
    });
    this.addCommand({
      id: "open-svg-image-editor",
      name: "Open SVG Image Editor for hovered SVG image",
      callback: () => {
        const target = this.hoveredSvgTarget ?? this.findSvgTargetAtPoint(this.lastPointerX, this.lastPointerY);
        if (target)
          void this.openSvgEditorModal(target);
        else
          new import_obsidian.Notice(getLocaleStrings().noticeHoverSvgPrompt);
      }
    });
  }
  onunload() {
    if (window.a1SvgQuickEditor === this) {
      window.a1SvgQuickEditor = null;
    }
    if (window.svgQuickEditor === this) {
      window.svgQuickEditor = null;
    }
    this.clearHover();
    this.clearHoveredSvgTarget();
    this.overlay?.close();
    this.overlay = null;
    this.activeModal?.remove();
    this.activeModal = null;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  matchesObsidianHotkey(evt, hotkey) {
    if (!hotkey || !hotkey.key)
      return false;
    const isMac = typeof navigator !== "undefined" && navigator.platform?.toUpperCase().includes("MAC");
    const mods = (hotkey.modifiers || []).map((m) => m.toLowerCase());
    const wantsCtrl = mods.includes("ctrl") || mods.includes("control") || !isMac && mods.includes("mod");
    const wantsMeta = mods.includes("meta") || mods.includes("cmd") || mods.includes("command") || isMac && mods.includes("mod");
    const wantsShift = mods.includes("shift");
    const wantsAlt = mods.includes("alt");
    if (evt.ctrlKey !== wantsCtrl)
      return false;
    if (evt.metaKey !== wantsMeta)
      return false;
    if (evt.shiftKey !== wantsShift)
      return false;
    if (evt.altKey !== wantsAlt)
      return false;
    const target = hotkey.key.toLowerCase();
    const pressedKey = (evt.key || "").toLowerCase();
    const pressedCode = (evt.code || "").toLowerCase();
    return pressedKey === target || pressedCode === `key${target}` || pressedCode === `digit${target}` || pressedCode === target;
  }
  matchesHotkey(evt, hotkeyStr) {
    if (!hotkeyStr || !hotkeyStr.trim())
      return false;
    const isMac = typeof navigator !== "undefined" && navigator.platform?.toUpperCase().includes("MAC");
    const parts = hotkeyStr.split("+").map((p) => p.trim().toLowerCase());
    const hasCtrl = parts.includes("ctrl") || parts.includes("control") || !isMac && parts.includes("mod");
    const hasMeta = parts.includes("meta") || parts.includes("cmd") || parts.includes("command") || isMac && parts.includes("mod");
    const hasShift = parts.includes("shift");
    const hasAlt = parts.includes("alt");
    const keyPart = parts.find((p) => !["ctrl", "control", "shift", "alt", "meta", "cmd", "command", "mod"].includes(p)) || "";
    if (evt.ctrlKey !== hasCtrl)
      return false;
    if (evt.metaKey !== hasMeta)
      return false;
    if (evt.shiftKey !== hasShift)
      return false;
    if (evt.altKey !== hasAlt)
      return false;
    const pressedKey = (evt.key || "").toLowerCase();
    const pressedCode = (evt.code || "").toLowerCase();
    const targetKey = keyPart.toLowerCase();
    return pressedKey === targetKey || pressedCode === `key${targetKey}` || pressedCode === `digit${targetKey}` || pressedCode === targetKey;
  }
  isSvgEditHotkey(evt) {
    if (this.matchesHotkey(evt, this.settings.openEditorHotkey))
      return true;
    if (this.matchesHotkey(evt, "Ctrl+Shift+Alt+I"))
      return true;
    if (this.matchesHotkey(evt, "Ctrl+Alt+Shift+I"))
      return true;
    if (this.matchesHotkey(evt, "Mod+Alt+Shift+I"))
      return true;
    if (this.matchesHotkey(evt, "Mod+Shift+Alt+I"))
      return true;
    const hkMgr = this.app?.hotkeyManager;
    if (hkMgr) {
      const commandIds = [
        "svg-quick-editor:edit-svg-text",
        "svg-quick-editor:open-svg-image-editor",
        "a1-svg-quick-editor:edit-svg-text",
        "a1-svg-quick-editor:open-svg-image-editor"
      ];
      for (const id of commandIds) {
        const list = [
          ...hkMgr.getHotkeys?.(id) || [],
          ...hkMgr.customKeys?.[id] || [],
          ...hkMgr.defaultKeys?.[id] || []
        ];
        for (const hk of list) {
          if (this.matchesObsidianHotkey(evt, hk))
            return true;
        }
      }
    }
    return false;
  }
  onKeyDown(evt) {
    if (this.isSvgEditHotkey(evt)) {
      evt.preventDefault();
      evt.stopPropagation();
      evt.stopImmediatePropagation();
      void this.executeEditSvgText();
      return;
    }
    if (evt.key === "F2" && !evt.repeat && !evt.altKey && !evt.metaKey && !evt.ctrlKey) {
      if (this.overlay)
        return;
      const el = this.lastPointerX > 0 || this.lastPointerY > 0 ? document.elementFromPoint(this.lastPointerX, this.lastPointerY) : null;
      const target = this.hoveredSvgTarget ?? (el ? this.matchSvgElement(el) : null);
      const text = this.hovered ?? (el ? findTextInCard(el, this.lastPointerX, this.lastPointerY) : null);
      const inModal = el?.closest(".a1-svg-modal-body, .svg-lightbox-content, .svg-lightbox-modal, .svg-lightbox-body") || document.querySelector(".svg-lightbox-content, .a1-svg-modal-body");
      if (text || target || inModal) {
        evt.preventDefault();
        evt.stopPropagation();
        evt.stopImmediatePropagation();
        void this.executeEditSvgText();
        return;
      }
    }
    if ((evt.ctrlKey || evt.metaKey) && !evt.altKey && !this.overlay) {
      const activeSvg = this.history.getActiveSvg();
      if (activeSvg) {
        if (evt.key === "z" || evt.key === "Z") {
          evt.preventDefault();
          evt.stopPropagation();
          evt.stopImmediatePropagation();
          if (evt.shiftKey) {
            this.redo();
          } else {
            this.undo();
          }
          return;
        }
        if (evt.key === "y" || evt.key === "Y") {
          evt.preventDefault();
          evt.stopPropagation();
          evt.stopImmediatePropagation();
          this.redo();
          return;
        }
      }
    }
  }
  undo(svg) {
    const res = this.history.undo(svg);
    if (res) {
      this.clearHover();
      new import_obsidian.Notice(getLocaleStrings().noticeUndo);
    }
    return res;
  }
  redo(svg) {
    const res = this.history.redo(svg);
    if (res) {
      this.clearHover();
      new import_obsidian.Notice(getLocaleStrings().noticeRedo);
    }
    return res;
  }
  isSvgDirty(svg) {
    return this.history.isDirty(svg);
  }
  registerActiveSvg(svg) {
    this.history.setActiveSvg(svg);
  }
  async saveCurrentSvg(svg) {
    const target = svg ?? this.history.getActiveSvg();
    if (!target)
      return;
    await this.persistSvg(target);
    this.history.markSaved(target);
  }
  discardCurrentSvg(svg) {
    const target = svg ?? this.history.getActiveSvg();
    if (!target)
      return;
    this.history.discard(target);
    this.clearHover();
  }
  clearSvgHistory(svg) {
    this.history.clear(svg);
  }
  async executeEditSvgText() {
    if (this.overlay)
      return;
    let elAtPoint = this.lastPointerX > 0 || this.lastPointerY > 0 ? document.elementFromPoint(this.lastPointerX, this.lastPointerY) : null;
    const activeModalContainer = document.querySelector(".svg-lightbox-content, .a1-svg-modal-body");
    if (!elAtPoint && activeModalContainer) {
      elAtPoint = activeModalContainer;
    }
    let textToEdit = asText(this.hovered);
    if (!textToEdit && elAtPoint) {
      textToEdit = findTextInCard(elAtPoint, this.lastPointerX, this.lastPointerY);
    }
    if (!textToEdit && this.hoveredSvgTarget) {
      textToEdit = findTextInCard(this.hoveredSvgTarget, this.lastPointerX, this.lastPointerY);
    }
    if (!textToEdit && activeModalContainer) {
      textToEdit = findTextInCard(activeModalContainer, this.lastPointerX, this.lastPointerY);
    }
    if (textToEdit && this.isInteractiveSvg(textToEdit)) {
      this.setHover(textToEdit);
      await this.beginEdit(textToEdit);
      return;
    }
    const svgTarget = this.hoveredSvgTarget ?? (elAtPoint ? this.matchSvgElement(elAtPoint) : null) ?? this.findSvgTargetAtPoint(this.lastPointerX, this.lastPointerY) ?? activeModalContainer;
    if (svgTarget) {
      const isModal = !!svgTarget.closest(".a1-svg-modal-body, .svg-lightbox-content, .svg-lightbox-modal, .svg-lightbox-body") || typeof svgTarget.matches === "function" && svgTarget.matches(".a1-svg-modal-body, .svg-lightbox-content, .svg-lightbox-modal, .svg-lightbox-body");
      if (isModal) {
        const svgEl = svgTarget instanceof SVGSVGElement ? svgTarget : svgTarget.closest("svg") ?? svgTarget.querySelector("svg");
        const fallbackText = svgEl ? findTextInCard(svgEl, this.lastPointerX, this.lastPointerY) : null;
        if (fallbackText) {
          this.setHover(fallbackText);
          await this.beginEdit(fallbackText);
          return;
        }
      } else {
        await this.openSvgEditorModal(svgTarget);
        return;
      }
    }
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (view && view.editor) {
      const cursor = view.editor.getCursor();
      for (let offset = 0; offset <= 2; offset++) {
        for (const sign of [0, -1, 1]) {
          if (offset === 0 && sign !== 0)
            continue;
          const lineNum = cursor.line + sign * offset;
          if (lineNum < 0 || lineNum >= view.editor.lineCount())
            continue;
          const lineText = view.editor.getLine(lineNum);
          const wikiMatch = lineText.match(/!\[\[([^\]|]+)(?:\|[^\]]*)?\]\]/);
          const mdMatch = lineText.match(/!\[[^\]]*\]\(([^)]+)\)/);
          const candidate = wikiMatch?.[1] || mdMatch?.[1];
          if (candidate && candidate.toLowerCase().includes(".svg")) {
            await this.openSvgEditorByPathOrLink(candidate.trim());
            return;
          }
        }
      }
    }
    new import_obsidian.Notice(getLocaleStrings().noticeHoverTextPrompt);
  }
  onPointerMove(evt) {
    this.lastPointerX = evt.clientX;
    this.lastPointerY = evt.clientY;
    if (this.dragging) {
      const dx = evt.clientX - this.dragging.lastX;
      const dy = evt.clientY - this.dragging.lastY;
      if (dx !== 0 || dy !== 0) {
        this.dragging.moved = true;
        this.dragging.lastX = evt.clientX;
        this.dragging.lastY = evt.clientY;
        this.translate(this.dragging.card, this.dragging.svg, dx, dy);
      }
      return;
    }
    if (this.overlay)
      return;
    const text = this.textFromEvent(evt);
    this.setHover(text);
    const svgTarget = this.svgTargetFromEvent(evt);
    this.setHoveredSvgTarget(svgTarget);
  }
  onPointerDown(evt) {
    if (!evt.altKey || evt.button !== 0)
      return;
    const target = evt.target instanceof Element ? evt.target : null;
    if (!target)
      return;
    let cloneTarget = resolveCloneTarget(target, evt.clientX, evt.clientY);
    if (!cloneTarget) {
      const text = this.textFromEvent(evt);
      if (text) {
        cloneTarget = resolveCloneTarget(text, evt.clientX, evt.clientY);
      }
    }
    if (!cloneTarget)
      return;
    const isSvg = typeof SVGSVGElement !== "undefined" && cloneTarget instanceof SVGSVGElement || (cloneTarget.localName || cloneTarget.tagName.toLowerCase()).endsWith("svg");
    const svg = isSvg ? cloneTarget : cloneTarget.ownerSVGElement ?? cloneTarget.closest("svg");
    if (!svg || !this.isInteractiveSvg(svg))
      return;
    evt.preventDefault();
    evt.stopPropagation();
    evt.stopImmediatePropagation();
    this.history.recordSnapshot(svg);
    const clone = cloneCard(cloneTarget, 12, 12);
    cloneTarget.parentElement?.appendChild(clone);
    this.dragging = {
      card: clone,
      svg,
      pointerId: evt.pointerId,
      lastX: evt.clientX,
      lastY: evt.clientY,
      moved: true
    };
  }
  onPointerUp(evt) {
    if (!this.dragging || evt.pointerId !== this.dragging.pointerId)
      return;
    const svg = this.dragging.svg;
    this.dragging = null;
    const inModal = !!svg.closest(".a1-svg-modal-body, .svg-lightbox-content, .svg-lightbox-modal, .svg-lightbox-body");
    if (!inModal) {
      void this.persistSvg(svg);
    }
  }
  textFromEvent(evt) {
    const clientX = evt.clientX;
    const clientY = evt.clientY;
    const path = typeof evt.composedPath === "function" ? evt.composedPath() : [];
    for (const node of path) {
      if (node instanceof Element) {
        const found = asText(node);
        if (found && this.isInteractiveSvg(found))
          return found;
      }
    }
    const t = evt.target;
    if (t instanceof Element) {
      const found = asText(t);
      if (found && this.isInteractiveSvg(found))
        return found;
      const cardText = findTextInCard(t, clientX, clientY);
      if (cardText && this.isInteractiveSvg(cardText))
        return cardText;
    }
    return null;
  }
  isInteractiveSvg(el) {
    const isSvg = typeof SVGSVGElement !== "undefined" && el instanceof SVGSVGElement || (el.localName || el.tagName.toLowerCase()).endsWith("svg");
    const svg = isSvg ? el : el.ownerSVGElement ?? el.closest("svg") ?? el.querySelector("svg");
    if (!svg)
      return false;
    return !!svg.closest(
      ".markdown-preview-view, .markdown-rendered, .view-content, .cm-content, .markdown-source-view, div[class*='block-language'], .internal-embed, .image-embed, .media-embed, .a1-svg-modal-body, .svg-lightbox-content, .svg-lightbox-modal, .svg-lightbox-body"
    );
  }
  svgTargetFromEvent(evt) {
    const path = typeof evt.composedPath === "function" ? evt.composedPath() : [];
    for (const node of path) {
      if (node instanceof Element) {
        const match = this.matchSvgElement(node);
        if (match)
          return match;
      }
    }
    if (evt.target instanceof Element) {
      return this.matchSvgElement(evt.target);
    }
    return null;
  }
  findSvgTargetAtPoint(x, y) {
    const el = x > 0 || y > 0 ? document.elementFromPoint(x, y) : null;
    if (!el)
      return null;
    return this.matchSvgElement(el);
  }
  matchSvgElement(el) {
    const embed = el.closest(".internal-embed, .image-embed, .media-embed, div[class*='block-language']") ?? el.querySelector(".internal-embed, .image-embed, .media-embed, div[class*='block-language']");
    if (embed) {
      const src = (embed.getAttribute("src") || "").toLowerCase();
      const img = embed.querySelector("img");
      const imgSrc = (img?.getAttribute("src") || "").toLowerCase();
      if (src.includes(".svg") || imgSrc.includes(".svg") || embed.querySelector("img[src*='.svg' i]")) {
        return embed;
      }
    }
    if (el instanceof HTMLImageElement) {
      const src = (el.getAttribute("src") || "").toLowerCase();
      if (src.includes(".svg"))
        return el;
    }
    const childImg = el.querySelector("img[src*='.svg' i]");
    if (childImg)
      return childImg;
    const modalContainer = el.closest(".svg-lightbox-content, .svg-lightbox-body, .a1-svg-modal-body");
    if (modalContainer)
      return modalContainer;
    if (el instanceof SVGSVGElement && isDiagramSvg(el) && this.isInteractiveSvg(el))
      return el;
    const parentSvg = el.closest("svg");
    if (parentSvg && isDiagramSvg(parentSvg) && this.isInteractiveSvg(parentSvg))
      return parentSvg;
    const childSvg = el.querySelector("svg");
    if (childSvg && isDiagramSvg(childSvg) && this.isInteractiveSvg(childSvg))
      return childSvg;
    return null;
  }
  setHover(text) {
    if (this.hovered === text)
      return;
    this.clearHover();
    this.hovered = text;
    text?.classList.add("a1-svg-hover-text");
  }
  clearHover() {
    this.hovered?.classList.remove("a1-svg-hover-text");
    this.hovered = null;
  }
  setHoveredSvgTarget(target) {
    if (this.hoveredSvgTarget === target)
      return;
    this.clearHoveredSvgTarget();
    this.hoveredSvgTarget = target;
    if (target && !(target instanceof SVGElement)) {
      target.classList.add("a1-svg-hover-image");
    }
  }
  clearHoveredSvgTarget() {
    if (this.hoveredSvgTarget && !(this.hoveredSvgTarget instanceof SVGElement)) {
      this.hoveredSvgTarget.classList.remove("a1-svg-hover-image");
    }
    this.hoveredSvgTarget = null;
  }
  async beginEdit(textEl) {
    const hit = resolveHit(textEl);
    const svg = textEl.ownerSVGElement;
    if (!hit || !svg)
      return;
    this.overlay?.close();
    const rect = textEl.getBoundingClientRect();
    const cs = getComputedStyle(textEl);
    this.overlay = openTextOverlay(document.body, {
      rect: { left: rect.left, top: rect.top, width: rect.width, height: rect.height },
      value: readText(hit.textEl),
      fontSize: cs.fontSize,
      fontFamily: cs.fontFamily,
      color: cs.fill || cs.color,
      onCommit: (value) => {
        this.overlay = null;
        this.history.recordSnapshot(svg);
        commitText(hit, value);
        const inModal = !!svg.closest(".a1-svg-modal-body, .svg-lightbox-content, .svg-lightbox-modal, .svg-lightbox-body");
        if (!inModal) {
          void this.persistSvg(svg);
        }
      },
      onCancel: () => {
        this.overlay = null;
      }
    });
  }
  translate(card, svg, dx, dy) {
    const ctm = svg.getScreenCTM();
    if (!ctm)
      return;
    const inv = ctm.inverse();
    nudge(card, inv.a * dx + inv.c * dy, inv.b * dx + inv.d * dy);
  }
  /**
   * Persists SVG changes.
   * If the SVG was loaded from a standalone .svg vault file (marked with data-a1-svg-path),
   * writes directly to that file and refreshes note images.
   * Otherwise splices into the active Markdown note.
   */
  async persistSvg(svg) {
    const svgPath = svg.getAttribute(SVG_PATH_ATTR);
    if (svgPath) {
      const file2 = this.app.vault.getAbstractFileByPath(svgPath);
      const live2 = serializeSvg(svg);
      if (file2 instanceof import_obsidian.TFile) {
        await this.app.vault.modify(file2, live2);
      } else {
        try {
          await this.app.vault.adapter.write(svgPath, live2);
        } catch (err) {
          console.error("Failed to write svg file via adapter:", err);
        }
      }
      this.refreshImgEmbeds(svgPath);
      window.dispatchEvent(new CustomEvent("a1-svg-updated", { detail: { path: svgPath, content: live2 } }));
      const name = svgPath.split("/").pop() || "SVG";
      new import_obsidian.Notice(getLocaleStrings().noticeSaved(name));
      this.clearHover();
      return;
    }
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    const file = view?.file ?? this.app.workspace.getActiveFile();
    if (!file)
      return;
    const marker = this.markerFor(svg);
    const live = serializeSvg(svg);
    await this.app.vault.process(file, (data) => {
      const span = matchSpan(data, this.domIndex(svg), marker);
      if (!span)
        return data;
      const stamped = ensureMarker(live, marker);
      return spliceSvg(data, span, stamped);
    });
    this.clearHover();
  }
  refreshImgEmbeds(filePath) {
    const filename = filePath.split("/").pop() || "";
    const encoded = encodeURIComponent(filename);
    const imgs = Array.from(document.querySelectorAll("img"));
    for (const img of imgs) {
      const src = img.getAttribute("src") || "";
      if (src.includes(filename) || src.includes(encoded)) {
        const clean = src.split("?")[0];
        img.setAttribute("src", `${clean}?t=${Date.now()}`);
      }
    }
  }
  markerFor(svg) {
    const existing = svg.getAttribute(MARK);
    if (existing)
      return existing;
    const marker = `s${this.domIndex(svg)}-${fileStamp(this.app.workspace.getActiveFile())}`;
    svg.setAttribute(MARK, marker);
    return marker;
  }
  domIndex(svg) {
    const root = svg.closest(".markdown-preview-view, .markdown-rendered") ?? document.body;
    const all = Array.from(root.querySelectorAll("svg"));
    const idx = all.indexOf(svg);
    return idx < 0 ? 0 : idx;
  }
  /**
   * Opens the full interactive SVG Image Editor Modal for a hovered note SVG image or element.
   */
  async openSvgEditorModal(target) {
    this.activeModal?.remove();
    this.activeModal = null;
    const i18n = getLocaleStrings();
    let file = null;
    let relPath = "";
    let rawSvgContent = "";
    let title = i18n.modalTitleDefault;
    const embed = target.closest(".internal-embed, .image-embed, .media-embed, div[class*='block-language']") ?? target.querySelector(".internal-embed, .image-embed, .media-embed, div[class*='block-language']") ?? target;
    const img = target instanceof HTMLImageElement ? target : embed?.querySelector("img");
    const rawSrc = img?.getAttribute("src") || (target instanceof HTMLImageElement ? target.src : "") || "";
    if (img || embed.classList?.contains("internal-embed") || embed.classList?.contains("image-embed") || rawSrc.includes(".svg")) {
      let filenameFromSrc = "";
      let directRelPath = "";
      if (rawSrc) {
        try {
          let decoded = decodeURIComponent(rawSrc.split("?")[0]);
          decoded = decoded.replace(/\\/g, "/");
          decoded = decoded.replace(/^[a-z]+:\/\/[^/]*\//i, "");
          decoded = decoded.replace(/^\/+/, "");
          const vaultBasePath = (this.app.vault.adapter?.basePath || "").replace(/\\/g, "/").replace(/^\/+/, "");
          if (vaultBasePath && decoded.toLowerCase().startsWith(vaultBasePath.toLowerCase())) {
            directRelPath = decoded.slice(vaultBasePath.length).replace(/^\/+/, "");
          }
          filenameFromSrc = decoded.split("/").pop() || "";
        } catch {
        }
      }
      const rawCandidates = [
        directRelPath,
        embed?.getAttribute("src") || "",
        embed?.getAttribute("data-src") || "",
        img?.getAttribute("alt") || "",
        img?.getAttribute("data-src") || "",
        filenameFromSrc
      ].filter((c) => !!c && !!c.trim());
      if (directRelPath && directRelPath.includes("/")) {
        const parts = directRelPath.split("/");
        for (let i = 1; i < parts.length; i++) {
          rawCandidates.push(parts.slice(i).join("/"));
        }
      }
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      const sourcePath = activeView?.file?.path || this.app.workspace.getActiveFile()?.path || "";
      for (const rawCand of rawCandidates) {
        const clean = rawCand.replace(/^\[\[/, "").replace(/\]\]$/, "").split("|")[0].trim();
        if (!clean)
          continue;
        if (sourcePath) {
          file = this.app.metadataCache.getFirstLinkpathDest(clean, sourcePath);
        }
        if (!file) {
          file = this.app.metadataCache.getFirstLinkpathDest(clean, "");
        }
        if (!file) {
          file = this.app.vault.getAbstractFileByPath(clean);
        }
        if (!file) {
          const allFiles = this.app.vault.getFiles();
          const cleanLower = clean.toLowerCase();
          file = allFiles.find(
            (f) => f.path.toLowerCase() === cleanLower || f.name.toLowerCase() === cleanLower || f.path.toLowerCase().endsWith("/" + cleanLower) || cleanLower.endsWith(".svg") && f.name.toLowerCase().endsWith(cleanLower) || filenameFromSrc && f.name.toLowerCase() === filenameFromSrc.toLowerCase()
          ) || null;
        }
        if (file && file.extension === "svg") {
          try {
            rawSvgContent = await this.app.vault.read(file);
            relPath = file.path;
            title = i18n.modalTitleNamed(file.name);
            break;
          } catch {
          }
        }
        if (!rawSvgContent) {
          try {
            const exists = await this.app.vault.adapter.exists(clean);
            if (exists) {
              rawSvgContent = await this.app.vault.adapter.read(clean);
              relPath = clean;
              title = i18n.modalTitleNamed(clean.split("/").pop() || "SVG");
              break;
            }
          } catch {
          }
        }
      }
    }
    if (!rawSvgContent && !img && !embed.classList?.contains("internal-embed") && !embed.classList?.contains("image-embed")) {
      const candidateSvg = target instanceof SVGSVGElement ? target : target.closest("svg") ?? target.querySelector("svg");
      if (candidateSvg && isDiagramSvg(candidateSvg)) {
        const svgPath = candidateSvg.getAttribute(SVG_PATH_ATTR);
        if (svgPath) {
          const f = this.app.vault.getAbstractFileByPath(svgPath);
          if (f instanceof import_obsidian.TFile)
            file = f;
          relPath = svgPath;
        }
        rawSvgContent = serializeSvg(candidateSvg);
        if (file)
          title = i18n.modalTitleNamed(file.name);
      }
    }
    if (!rawSvgContent) {
      new import_obsidian.Notice(i18n.noticeCannotParse);
      return;
    }
    this.renderModalWithContent(rawSvgContent, relPath || file?.path || "", title);
  }
  async openSvgEditorByPathOrLink(linkPath) {
    const clean = linkPath.replace(/^\[\[/, "").replace(/\]\]$/, "").split("|")[0].trim();
    if (!clean)
      return;
    const i18n = getLocaleStrings();
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    const sourcePath = activeView?.file?.path || this.app.workspace.getActiveFile()?.path || "";
    let file = null;
    if (sourcePath)
      file = this.app.metadataCache.getFirstLinkpathDest(clean, sourcePath);
    if (!file)
      file = this.app.metadataCache.getFirstLinkpathDest(clean, "");
    if (!file)
      file = this.app.vault.getAbstractFileByPath(clean);
    if (!file) {
      const cleanLower = clean.toLowerCase();
      file = this.app.vault.getFiles().find(
        (f) => f.path.toLowerCase() === cleanLower || f.name.toLowerCase() === cleanLower || f.path.toLowerCase().endsWith("/" + cleanLower)
      ) || null;
    }
    let rawSvgContent = "";
    let relPath = file ? file.path : clean;
    if (file) {
      try {
        rawSvgContent = await this.app.vault.read(file);
      } catch {
      }
    }
    if (!rawSvgContent) {
      try {
        if (await this.app.vault.adapter.exists(clean)) {
          rawSvgContent = await this.app.vault.adapter.read(clean);
          relPath = clean;
        }
      } catch {
      }
    }
    if (!rawSvgContent) {
      new import_obsidian.Notice(i18n.noticeCannotParse);
      return;
    }
    const name = file ? file.name : clean.split("/").pop() || "SVG";
    this.renderModalWithContent(rawSvgContent, relPath, i18n.modalTitleNamed(name));
  }
  renderModalWithContent(rawSvgContent, relPath, title) {
    const i18n = getLocaleStrings();
    if (!rawSvgContent.includes("viewBox") && !rawSvgContent.includes("viewbox")) {
      const widthMatch = rawSvgContent.match(/width=["']?(\d+(?:\.\d+)?)px?["']?/i);
      const heightMatch = rawSvgContent.match(/height=["']?(\d+(?:\.\d+)?)px?["']?/i);
      if (widthMatch && heightMatch) {
        const w = widthMatch[1];
        const h = heightMatch[1];
        rawSvgContent = rawSvgContent.replace(/<svg\b/i, `<svg viewBox="0 0 ${w} ${h}"`);
      }
    }
    if (relPath) {
      rawSvgContent = rawSvgContent.replace(/<svg\b/i, `<svg ${SVG_PATH_ATTR}="${relPath}"`);
    }
    const backdrop = document.createElement("div");
    backdrop.className = "a1-svg-modal-backdrop";
    const dialog = document.createElement("div");
    dialog.className = "a1-svg-modal-dialog";
    const header = document.createElement("div");
    header.className = "a1-svg-modal-header";
    const titleRow = document.createElement("div");
    titleRow.className = "a1-svg-modal-title-row";
    const titleDiv = document.createElement("div");
    titleDiv.className = "a1-svg-modal-title";
    titleDiv.innerHTML = `
			<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--interactive-accent, #7c9cff)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="flex-shrink:0;">
				<rect x="3" y="3" width="18" height="18" rx="2" ry="2"/>
				<circle cx="8.5" cy="8.5" r="1.5"/>
				<polyline points="21 15 16 10 5 21"/>
			</svg>
			<span>${title}</span>
		`;
    const hintsDiv = document.createElement("div");
    hintsDiv.className = "a1-svg-modal-hints";
    hintsDiv.innerHTML = `
			<span class="a1-svg-modal-badge">${i18n.badgeEdit}</span>
			<span class="a1-svg-modal-badge">${i18n.badgeDelete}</span>
			<span class="a1-svg-modal-badge">${i18n.badgeClone}</span>
			<span class="a1-svg-modal-badge">${i18n.badgeUndoRedo}</span>
		`;
    titleRow.appendChild(titleDiv);
    titleRow.appendChild(hintsDiv);
    const actionGroup = document.createElement("div");
    actionGroup.className = "a1-svg-modal-actions";
    if (relPath) {
      const openInTabBtn = document.createElement("button");
      openInTabBtn.type = "button";
      openInTabBtn.className = "a1-svg-modal-tab-btn";
      openInTabBtn.textContent = i18n.openInTab;
      openInTabBtn.title = "Open note/file in Obsidian";
      openInTabBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.app.workspace.openLinkText(relPath, "", false);
      });
      actionGroup.appendChild(openInTabBtn);
    }
    const closeBtn = document.createElement("button");
    closeBtn.type = "button";
    closeBtn.className = "a1-svg-modal-close";
    closeBtn.textContent = "\u2715";
    closeBtn.title = i18n.closeTooltip;
    actionGroup.appendChild(closeBtn);
    header.appendChild(titleRow);
    header.appendChild(actionGroup);
    const body = document.createElement("div");
    body.className = "a1-svg-modal-body";
    body.innerHTML = rawSvgContent;
    const modalSvg = body.querySelector("svg");
    if (modalSvg) {
      this.history.setActiveSvg(modalSvg);
    }
    dialog.appendChild(header);
    dialog.appendChild(body);
    backdrop.appendChild(dialog);
    let isConfirming = false;
    const closeModal = () => {
      this.clearHover();
      backdrop.remove();
      if (this.activeModal === backdrop)
        this.activeModal = null;
      window.removeEventListener("keydown", keyHandler);
    };
    const requestClose = () => {
      if (isConfirming)
        return;
      this.clearHover();
      if (modalSvg && this.history.isDirty(modalSvg)) {
        isConfirming = true;
        this.promptSaveConfirmation(
          async () => {
            isConfirming = false;
            await this.persistSvg(modalSvg);
            this.history.markSaved(modalSvg);
            closeModal();
          },
          () => {
            isConfirming = false;
            this.history.discard(modalSvg);
            closeModal();
          },
          () => {
            isConfirming = false;
          }
        );
        return;
      }
      closeModal();
    };
    closeBtn.addEventListener("click", requestClose);
    backdrop.addEventListener("click", (e) => {
      if (e.target === backdrop)
        requestClose();
    });
    backdrop.addEventListener("contextmenu", (e) => {
      if (this.overlay)
        return;
      if (e.target === backdrop || e.target.closest(".a1-svg-modal-dialog")) {
        e.preventDefault();
        requestClose();
      }
    });
    const keyHandler = (e) => {
      if (e.key === "Escape" && !this.overlay && !isConfirming) {
        e.preventDefault();
        requestClose();
      }
    };
    window.addEventListener("keydown", keyHandler);
    document.body.appendChild(backdrop);
    this.activeModal = backdrop;
  }
  promptSaveConfirmation(onSave, onDiscard, onCancel) {
    const i18n = getLocaleStrings();
    const overlay = document.createElement("div");
    overlay.className = "a1-svg-confirm-overlay";
    const card = document.createElement("div");
    card.className = "a1-svg-confirm-dialog";
    const title = document.createElement("div");
    title.className = "a1-svg-confirm-title";
    title.textContent = i18n.confirmSaveTitle;
    const desc = document.createElement("div");
    desc.className = "a1-svg-confirm-desc";
    desc.textContent = i18n.confirmSaveDesc;
    const btnRow = document.createElement("div");
    btnRow.className = "a1-svg-confirm-buttons";
    const saveBtn = document.createElement("button");
    saveBtn.className = "mod-cta";
    saveBtn.textContent = i18n.btnSave;
    const discardBtn = document.createElement("button");
    discardBtn.className = "mod-warning";
    discardBtn.textContent = i18n.btnDiscard;
    const cancelBtn = document.createElement("button");
    cancelBtn.className = "";
    cancelBtn.textContent = i18n.btnCancel;
    btnRow.appendChild(saveBtn);
    btnRow.appendChild(discardBtn);
    btnRow.appendChild(cancelBtn);
    card.appendChild(title);
    card.appendChild(desc);
    card.appendChild(btnRow);
    overlay.appendChild(card);
    document.body.appendChild(overlay);
    const cleanup = () => {
      overlay.remove();
      window.removeEventListener("keydown", onKey, true);
    };
    const doSave = async () => {
      cleanup();
      await onSave();
    };
    const doDiscard = () => {
      cleanup();
      onDiscard();
    };
    const doCancel = () => {
      cleanup();
      onCancel();
    };
    saveBtn.addEventListener("click", () => void doSave());
    discardBtn.addEventListener("click", doDiscard);
    cancelBtn.addEventListener("click", doCancel);
    overlay.addEventListener("click", (e) => {
      if (e.target === overlay)
        doCancel();
    });
    const onKey = (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        void doSave();
      } else if (e.key === "Escape") {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        doCancel();
      }
    };
    window.addEventListener("keydown", onKey, true);
    saveBtn.focus();
  }
};
var A1SvgQuickEditorSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const i18n = getLocaleStrings();
    new import_obsidian.Setting(containerEl).setName(i18n.settingHotkeyName).setDesc(i18n.settingHotkeyDesc).addText((text) => {
      text.setValue(this.plugin.settings.openEditorHotkey);
      text.inputEl.addEventListener("keydown", async (e) => {
        if (["Control", "Shift", "Alt", "Meta"].includes(e.key))
          return;
        e.preventDefault();
        e.stopPropagation();
        const parts = [];
        if (e.ctrlKey)
          parts.push("Ctrl");
        if (e.shiftKey)
          parts.push("Shift");
        if (e.altKey)
          parts.push("Alt");
        if (e.metaKey)
          parts.push("Cmd");
        parts.push(e.key.toUpperCase());
        const combination = parts.join("+");
        text.setValue(combination);
        this.plugin.settings.openEditorHotkey = combination;
        await this.plugin.saveSettings();
        new import_obsidian.Notice(i18n.settingUpdatedNotice(combination));
      });
    }).addExtraButton((btn) => {
      btn.setIcon("reset").setTooltip(i18n.settingResetTooltip).onClick(async () => {
        this.plugin.settings.openEditorHotkey = DEFAULT_SETTINGS.openEditorHotkey;
        await this.plugin.saveSettings();
        this.display();
        new import_obsidian.Notice(i18n.settingResetNotice);
      });
    });
  }
};
function fileStamp(file) {
  if (!file)
    return "x";
  let h = 0;
  const s = file.path;
  for (let i = 0; i < s.length; i++)
    h = h * 33 + s.charCodeAt(i) >>> 0;
  return h.toString(36);
}
